-- Conteúdo inicial (rascunho editorial para revisão). Publicado, gratuito.

with p as (
  insert into public.programs (slug, kind, title, summary, access, published, position)
  values ('clt-para-negocio', 'journey', $j${"pt-BR": "CLT → Negócio", "en": "Employee → Business"}$j$::jsonb, $j${"pt-BR": "Uma jornada guiada para sair do emprego com os pés no chão: clareza, finanças, validação, formalização e os primeiros 90 dias.", "en": "A guided journey to leave a job with your feet on the ground: clarity, finances, validation, formalization and the first 90 days."}$j$::jsonb, 'free', true, 0)
  on conflict (slug) do nothing
  returning id
)
insert into public.program_lessons (program_id, position, title, body, duration_minutes, steps)
select * from (values
((select id from p), 0, $j${"pt-BR": "Clareza: por que e para quê", "en": "Clarity: why and what for"}$j$::jsonb, $j${"pt-BR": "Antes de qualquer planilha, vale entender o que você quer mudar. Sair do emprego costuma ser a resposta para uma pergunta que ainda não foi feita com clareza: mais liberdade? mais renda? mais sentido? outro ritmo de vida?\n\nNão existe motivo certo ou errado. Existe motivo que sustenta você quando o caminho ficar difícil, e motivo que some na primeira semana ruim.\n\nNesta etapa você não decide nada. Só escreve, com honestidade, de onde está saindo e para onde quer ir.", "en": "Before any spreadsheet, it helps to understand what you want to change. Leaving a job is often the answer to a question that was never asked clearly: more freedom? more income? more meaning? a different pace of life?\n\nThere is no right or wrong reason. There are reasons that carry you when the road gets hard, and reasons that vanish in the first bad week.\n\nAt this stage you decide nothing. You just write, honestly, where you are leaving from and where you want to go."}$j$::jsonb, 10, $j$[{"pt-BR": "Escrever em uma página por que quero mudar de vida profissional", "en": "Write one page on why I want to change my professional life"}, {"pt-BR": "Definir o que eu não abriria mão (valores, horários, renda mínima)", "en": "Define what I would not give up (values, hours, minimum income)"}, {"pt-BR": "Descrever como seria uma semana boa no meu negócio", "en": "Describe what a good week in my business would look like"}]$j$::jsonb),
((select id from p), 1, $j${"pt-BR": "Seu ponto de partida financeiro", "en": "Your financial starting point"}$j$::jsonb, $j${"pt-BR": "A maior causa de abandono do negócio no começo não é falta de ideia: é falta de fôlego. O dinheiro compra tempo para aprender, errar e ajustar.\n\nUse o Plano Financeiro do app para ver seu custo mensal real (despesas + parcelas). Uma referência comum é ter de 6 a 12 meses desse custo guardados antes de depender do negócio. Se isso parece distante, tudo bem: a jornada serve justamente para construir a ponte aos poucos.\n\nDívidas caras (cartão, cheque especial) pesam mais do que quase qualquer outro risco. Elas costumam entrar antes na fila.", "en": "The main reason businesses are abandoned early is not a lack of ideas: it is a lack of runway. Money buys time to learn, make mistakes and adjust.\n\nUse the app's Financial Plan to see your real monthly cost (expenses + payments). A common reference is to have 6 to 12 months of that cost saved before relying on the business. If that feels far away, that is fine: this journey exists to build the bridge little by little.\n\nExpensive debt (credit cards, overdraft) weighs more than almost any other risk. It usually goes first in line."}$j$::jsonb, 15, $j$[{"pt-BR": "Cadastrar rendas, despesas e dívidas no Plano Financeiro", "en": "Add income, expenses and debts to the Financial Plan"}, {"pt-BR": "Definir minha meta de reserva em meses de custo", "en": "Set my reserve goal in months of cost"}, {"pt-BR": "Escolher uma dívida cara para priorizar", "en": "Pick one expensive debt to prioritize"}]$j$::jsonb),
((select id from p), 2, $j${"pt-BR": "Escolha da ideia: problema, pessoa e oferta", "en": "Choosing the idea: problem, person and offer"}$j$::jsonb, $j${"pt-BR": "Bons negócios pequenos começam por um problema real de uma pessoa específica, não por um produto bonito. Pergunte: quem sofre com isso? quanto já gasta (em dinheiro ou tempo) para resolver? por que me ouviria?\n\nUse o que você já tem: experiência de trabalho, contatos, habilidades. Quem muda de carreira raramente começa do zero; começa de outro ângulo.\n\nEscolha uma ideia para testar, não \"a\" ideia da vida. Testar é barato; acertar de primeira é raro.", "en": "Good small businesses start from a real problem of a specific person, not from a nice product. Ask: who suffers from this? how much do they already spend (in money or time) to solve it? why would they listen to me?\n\nUse what you already have: work experience, contacts, skills. People changing careers rarely start from zero; they start from another angle.\n\nPick an idea to test, not \"the\" idea of your life. Testing is cheap; getting it right the first time is rare."}$j$::jsonb, 15, $j$[{"pt-BR": "Listar 3 ideias de negócio ligadas ao que eu já sei fazer", "en": "List 3 business ideas tied to what I already know how to do"}, {"pt-BR": "Descrever, para cada uma, quem é o cliente e qual problema resolve", "en": "For each, describe who the customer is and what problem it solves"}, {"pt-BR": "Escolher uma ideia para validar nas próximas semanas", "en": "Pick one idea to validate over the next weeks"}]$j$::jsonb),
((select id from p), 3, $j${"pt-BR": "Validar sem largar o emprego", "en": "Validate without leaving your job"}$j$::jsonb, $j${"pt-BR": "Validar é descobrir se alguém paga pelo que você oferece antes de investir muito. O sinal mais forte é um cliente real pagando, mesmo que pouco.\n\nComece pequeno: converse com cinco pessoas do seu público, ofereça uma versão simples do serviço, venda para alguém conhecido. Faça isso em noites e fins de semana, respeitando seu contrato e evitando conflito com o empregador.\n\nCada conversa ensina algo. O objetivo desta etapa é a primeira venda e o que ela ensinou.", "en": "Validating means finding out whether someone pays for what you offer before investing much. The strongest signal is a real customer paying, even a little.\n\nStart small: talk to five people in your audience, offer a simple version of the service, sell to someone you know. Do this on evenings and weekends, respecting your contract and avoiding conflict with your employer.\n\nEvery conversation teaches something. The goal of this stage is the first sale and what it taught you."}$j$::jsonb, 15, $j$[{"pt-BR": "Conversar com 5 pessoas do meu público-alvo", "en": "Talk to 5 people in my target audience"}, {"pt-BR": "Montar uma oferta simples com preço", "en": "Put together a simple offer with a price"}, {"pt-BR": "Fazer a primeira venda (mesmo pequena)", "en": "Make the first sale (even a small one)"}]$j$::jsonb),
((select id from p), 4, $j${"pt-BR": "Formalização, impostos e seus direitos", "en": "Formalization, taxes and your rights"}$j$::jsonb, $j${"pt-BR": "Este conteúdo é educativo e não substitui um contador ou advogado. As regras mudam; confirme sempre os valores e limites vigentes.\n\nNo Brasil, muitos começam como MEI (limite anual de faturamento e atividades permitidas definidos em lei) e depois migram para ME no Simples Nacional. Um contador ajuda a escolher o enquadramento e a evitar surpresas.\n\nSobre o emprego CLT: pedir demissão, ser demitido e fazer acordo (art. 484-A) geram direitos diferentes sobre FGTS, multa, aviso prévio e seguro-desemprego. Entenda essas diferenças antes de definir a data de saída, pois ela muda quanto dinheiro de ponte você terá.", "en": "This content is educational and does not replace an accountant or lawyer. Rules change; always confirm current amounts and limits.\n\nIn Brazil, many start as MEI (annual revenue limit and allowed activities set by law) and later move to ME under Simples Nacional. An accountant helps choose the right framework and avoid surprises.\n\nOn the CLT job: resigning, being dismissed and a mutual agreement (art. 484-A) create different rights over FGTS, penalty, notice period and unemployment insurance. Understand these differences before setting an exit date, because it changes how much bridge money you will have.\n\nIf you are outside Brazil, ask a local accountant about the equivalent: business structure, taxes and what you lose or keep when leaving employment."}$j$::jsonb, 15, $j$[{"pt-BR": "Marcar uma conversa com um contador", "en": "Book a conversation with an accountant"}, {"pt-BR": "Anotar o que muda no meu caso entre pedir demissão e acordo", "en": "Note what changes in my case between resigning and a mutual agreement"}, {"pt-BR": "Escolher o formato legal do negócio", "en": "Choose the legal structure of the business"}]$j$::jsonb),
((select id from p), 5, $j${"pt-BR": "O plano de transição (90 dias)", "en": "The transition plan (90 days)"}$j$::jsonb, $j${"pt-BR": "Com ideia validada e números na mesa, defina a ponte: uma data de saída, quanto de reserva você terá nela, quanto o negócio precisa faturar para cobrir o custo mínimo e o que acontece se não chegar lá (plano B).\n\nTransições graduais costumam ser mais seguras: reduzir carga, negociar horário, ou sair só depois de o negócio cobrir parte do custo.\n\nTransforme isso em projeto: este app cria um projeto com os passos práticos da jornada para você acompanhar e enviar passos para o seu dia.", "en": "With a validated idea and numbers on the table, define the bridge: an exit date, how much reserve you will have by then, how much the business needs to bring in to cover the minimum cost and what happens if it does not get there (plan B).\n\nGradual transitions tend to be safer: reducing workload, negotiating hours, or leaving only after the business covers part of the cost.\n\nTurn this into a project: this app creates a project with the journey's practical steps so you can track them and send steps to your day."}$j$::jsonb, 15, $j$[{"pt-BR": "Definir a data-alvo de saída e a reserva mínima nela", "en": "Set the target exit date and the minimum reserve by then"}, {"pt-BR": "Calcular o faturamento mínimo mensal do negócio", "en": "Calculate the business's minimum monthly revenue"}, {"pt-BR": "Escrever o plano B se a meta não for atingida", "en": "Write plan B if the goal is not met"}]$j$::jsonb),
((select id from p), 6, $j${"pt-BR": "Os primeiros 90 dias do negócio", "en": "The first 90 days of the business"}$j$::jsonb, $j${"pt-BR": "Nos primeiros meses, o trabalho é simples e exigente: vender, entregar bem, cobrar e separar o dinheiro da empresa do seu.\n\nCrie uma rotina fixa de prospecção (todo dia um pouco), registre o que entra e sai, e reserve uma parte de cada venda para impostos. Revise os números uma vez por semana.\n\nEspere oscilações. Um mês fraco não é veredito; é informação para ajustar oferta, preço ou canal.", "en": "In the first months, the work is simple and demanding: sell, deliver well, charge and keep company money apart from yours.\n\nCreate a fixed prospecting routine (a little every day), record what comes in and goes out, and set aside part of each sale for taxes. Review the numbers once a week.\n\nExpect swings. A weak month is not a verdict; it is information to adjust offer, price or channel."}$j$::jsonb, 10, $j$[{"pt-BR": "Criar rotina diária de prospecção (30 min)", "en": "Create a daily prospecting routine (30 min)"}, {"pt-BR": "Abrir uma conta separada para o negócio", "en": "Open a separate account for the business"}, {"pt-BR": "Reservar % de cada venda para impostos", "en": "Set aside a % of each sale for taxes"}]$j$::jsonb),
((select id from p), 7, $j${"pt-BR": "Cuidar de você na travessia", "en": "Taking care of yourself on the crossing"}$j$::jsonb, $j${"pt-BR": "Mudar de vida mexe com identidade, segurança e relações. É normal sentir medo, empolgação e dúvida no mesmo dia.\n\nMantenha uma rede de apoio: alguém que escute sem tentar resolver. Preserve sono, movimento e descanso, que sustentam qualquer plano. Use a Gratidão e as Afirmações do app como âncoras diárias.\n\nSe em algum momento o caminho pedir ajuste, ajustar não é fracassar. É planejar de novo com mais informação.", "en": "Changing your life stirs identity, security and relationships. It is normal to feel fear, excitement and doubt on the same day.\n\nKeep a support network: someone who listens without trying to fix. Protect sleep, movement and rest, which sustain any plan. Use the app's Gratitude and Affirmations as daily anchors.\n\nIf at some point the path calls for adjustment, adjusting is not failing. It is planning again with more information."}$j$::jsonb, 10, $j$[{"pt-BR": "Combinar com uma pessoa de confiança um check-in semanal", "en": "Agree on a weekly check-in with someone I trust"}, {"pt-BR": "Definir uma prática diária de descanso ou movimento", "en": "Define a daily rest or movement practice"}, {"pt-BR": "Registrar uma gratidão por dia durante a transição", "en": "Log one gratitude a day during the transition"}]$j$::jsonb)
) as v(program_id, position, title, body, duration_minutes, steps)
where exists (select 1 from p);

with p as (
  insert into public.programs (slug, kind, title, summary, access, published, position)
  values ('do-sonho-a-acao', 'program', $j${"pt-BR": "Do sonho à ação", "en": "From dream to action"}$j$::jsonb, $j${"pt-BR": "Três aulas curtas para usar o Plano A do jeito certo: sonho, hábito e revisão.", "en": "Three short lessons to use Plano A the right way: dream, habit and review."}$j$::jsonb, 'free', true, 0)
  on conflict (slug) do nothing
  returning id
)
insert into public.program_lessons (program_id, position, title, body, duration_minutes, steps)
select * from (values
((select id from p), 0, $j${"pt-BR": "Sonho, objetivo, ação", "en": "Dream, goal, action"}$j$::jsonb, $j${"pt-BR": "Um sonho vira realidade quando é traduzido em objetivos com prazo e em ações pequenas o bastante para caber em um dia.\n\nNo Plano A, a ordem é essa: registre o sonho (Sonhos), declare onde quer estar em 6 meses, 1, 5 e 10 anos (Objetivos) e escolha hoje uma ação (Minha Ação).", "en": "A dream becomes real when it is translated into goals with deadlines and actions small enough to fit in a day.\n\nIn Plano A the order is this: record the dream (Dreams), declare where you want to be in 6 months, 1, 5 and 10 years (Goals) and pick one action today (My Action)."}$j$::jsonb, 5, $j$[{"pt-BR": "Registrar 3 sonhos", "en": "Record 3 dreams"}, {"pt-BR": "Preencher os objetivos de 6 meses e 1 ano", "en": "Fill in the 6-month and 1-year goals"}, {"pt-BR": "Escolher uma ação para hoje", "en": "Pick one action for today"}]$j$::jsonb),
((select id from p), 1, $j${"pt-BR": "Hábitos que sustentam o plano", "en": "Habits that sustain the plan"}$j$::jsonb, $j${"pt-BR": "Motivação oscila; hábitos permanecem. Escolha um hábito pequeno, ligado a algo que você já faz todos os dias, e proteja a sequência sem culpa: um dia sem registro não apaga o que você construiu.", "en": "Motivation fluctuates; habits stay. Choose a small habit tied to something you already do every day and protect the streak without guilt: a day without a check-in does not erase what you built."}$j$::jsonb, 5, $j$[{"pt-BR": "Criar um hábito de 2 minutos", "en": "Create a 2-minute habit"}, {"pt-BR": "Ligar o hábito a um gatilho do dia", "en": "Tie the habit to a daily trigger"}]$j$::jsonb),
((select id from p), 2, $j${"pt-BR": "Revisão semanal em 10 minutos", "en": "A 10-minute weekly review"}$j$::jsonb, $j${"pt-BR": "Uma vez por semana, olhe para o que avançou, o que aprendeu e qual é o próximo passo. A página de Progresso mostra sua constância sem marcar falhas: use-a como espelho, não como cobrança.", "en": "Once a week, look at what moved forward, what you learned and what the next step is. The Progress page shows your consistency without marking failures: use it as a mirror, not as a scoreboard."}$j$::jsonb, 5, $j$[{"pt-BR": "Marcar a revisão semanal na agenda", "en": "Put the weekly review on the calendar"}, {"pt-BR": "Escolher o foco da próxima semana", "en": "Choose next week's focus"}]$j$::jsonb)
) as v(program_id, position, title, body, duration_minutes, steps)
where exists (select 1 from p);

with p as (
  insert into public.programs (slug, kind, title, summary, access, published, position)
  values ('mentalizacao-dia-do-sonho', 'meditation', $j${"pt-BR": "O dia em que o sonho acontece", "en": "The day the dream happens"}$j$::jsonb, $j${"pt-BR": "Uma mentalização guiada de cerca de 8 minutos.", "en": "A guided visualization of about 8 minutes."}$j$::jsonb, 'free', true, 0)
  on conflict (slug) do nothing
  returning id
)
insert into public.program_lessons (program_id, position, title, body, duration_minutes, steps)
select * from (values
((select id from p), 0, $j${"pt-BR": "Mentalização: o dia em que o sonho acontece", "en": "Visualization: the day the dream happens"}$j$::jsonb, $j${"pt-BR": "Procure um lugar tranquilo e sente-se com a coluna confortável. Feche os olhos, se for confortável para você.\n\nRespire fundo três vezes, soltando o ar devagar. Sinta o peso do corpo no apoio.\n\nEscolha um sonho seu. Imagine o dia em que ele se realiza: onde você está? quem está por perto? o que você vê, ouve e sente no corpo? Fique nos detalhes por alguns minutos, sem pressa e sem julgar.\n\nAgora pergunte: qual é o menor passo que eu posso dar hoje na direção desse dia? Deixe a resposta surgir.\n\nRespire fundo mais uma vez e, quando quiser, abra os olhos. Anote o passo no app.", "en": "Find a quiet place and sit with a comfortable spine. Close your eyes if that feels comfortable.\n\nBreathe deeply three times, letting the air out slowly. Feel the weight of your body on its support.\n\nChoose one of your dreams. Imagine the day it comes true: where are you? who is nearby? what do you see, hear and feel in your body? Stay with the details for a few minutes, without hurry and without judging.\n\nNow ask: what is the smallest step I can take today toward that day? Let the answer come.\n\nTake one more deep breath and, when you wish, open your eyes. Write the step down in the app."}$j$::jsonb, 8, $j$[{"pt-BR": "Anotar o passo que surgiu como ação de hoje", "en": "Write down the step that came up as today's action"}]$j$::jsonb)
) as v(program_id, position, title, body, duration_minutes, steps)
where exists (select 1 from p);
